### ISSUE TITLE
Which one should I use?

### ISSUE THREAD

**Issue by MAZ12211** [marek-saji/po-csv#19]
I have a large po file (Arabic language as the target and English as the source language) and we want to use a spreadsheet, but I don't know which one I have to use..

Can you tell me the difference between csv2po and your converter? beyond the plural forms (I really don't how this would affect us) and the notes.

edit: doesn't merge for whatever reason, so I'm sticking to csv2po

**Comment by marek-saji** [comment]
Plural forms and including notes to translators is the only difference, as far as I know. You are probably better off sticking with csv2po, because my guess it’s more actively maintained. I’m no longer actively using `po-csv` for anything, so only fixing some bugs, if anybody reports anything.

Speaking of which — even if you stick to csv2po — if you found some files that po-csv didn’t work with correctly, I would appreciate if you send them my way. Might be you found a bug. :slightly_smiling_face: I can’t promise how fast I’d fix it, but I’d look into to.
